blog: actuality ia machineLearning tresor agriculture event cinema music ric sport techno

ia:
	@node ia.js
machineLearning:
	@node MachineLearning/machineLearning.js
tresor:
	@node Tresorerie/tresorerie.js
actuality:
	@node actuality/hacktuality.js
agriculture:
	@node agriculture/agriculture.js
event:
	@node event/event.js
cinema:
	@node video/cinema.js
music:
	@node Music/music.js
ric:
	@node RIC/ric.js
sport:
	@node JO/sport.js
techno:	
	@node Technologie/Technologie.js